AnswerBot/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from landing import urls


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'landing.views.login'),
    url(r'^index/', include('landing.urls', namespace='landing')),
]

landing/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^bot/', views.bot, name='bot'),
]

landing/models.py
from django.db import models

class Product(models.Model):
	des_product = models.CharField(max_length=500)
	avg_price = models.FloatField(default=0)
	def __str__(self):
		return self.des_product
		return self.avg_price

landing/forms.py
from django import forms

class Search(forms.Form):
	q = forms.CharField(label='Busca un producto', max_length=250, required=True)

landing/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from .forms import Search
import urllib.request
import json
from . import preguntas_mercadolibre
from .models import Product

# Create your views here.
def login(request):
	return render(request, 'landing/login.html')

def index(request):
	prices = []
	if request.method == 'GET':
		form = Search()
		q = request.GET.get('q', None)
		if (q is not None) and (q != ""):
			url = "https://api.mercadolibre.com/sites/MLM/search?q={}".format(q.replace(' ', '%20'))
			print("*" * 20)
			print(url)
			print("*" * 20)
			with urllib.request.urlopen(url) as response: data = response.read()
			string_url = data.decode(encoding='UTF-8')
			resp = json.loads(string_url)
			length = len(resp['results'])
			print(length)
			for i in range(0, length):
				prices.append(resp['results'][i]['price'])
			average_price = sum(prices)/len(prices)
			print(average_price)
			return render(request, 'landing/index.html', {'form': form, 'precio': average_price})
	elif request.method == 'POST':
		form = Search()
		return render(request, 'landing/index.html', {'form': form})
	form = Search()
	return render(request, 'landing/index.html', {'form': form})

def bot(request):
	p = json.loads(preguntas_mercadolibre.obtener_respuestas())
	#p = p.json()
	print(p)
	res = []
	for i in p:
		temp_dict = {
			'image': i["product"]["pictures"][0]["url"],
			'title': i["product"]["title"],
			'questions': [],
		}
		# texto = i["product"]["title"]+"</br>"+"<img src=\""+i["product"]["pictures"][0]["url"]+"\" >"
		for preguntas in i["question_answers"]:
			if(preguntas["answer"]==""):
				t2 = {
					'question': preguntas["question"],
					'answer': "No se pudo generar",
				}
			else:
				t2 = {
					'question': preguntas["question"],
					'answer': preguntas["answer"],
				}
			temp_dict['questions'].append(t2)
			# texto = texto+"<br>Pregunta: "+preguntas["question"]+"<br>Respuesta automática: "+preguntas["answer"]
		res.append(temp_dict)
	return render(request, 'landing/preguntas.html', {'preguntas': res})

landing/templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Album</title>
    <!-- CDN Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- NavBar -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">Album</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="">Category<span class="sr-only">(current)</span></a></li>
                    <li><a href="">Photo</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Action
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="">Upload</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Log In</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block section %}
        {% endblock section %}
    </div>
    <div class="container">
        {% block maincontent %}
        {% endblock maincontent %}
    </div>
</body>
</html>

landing/templates/landing/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<div>
		<form method="get">
			{% csrf_token %}
			{{ form }}
		<input type="submit" placeholder="Checa los precios papi"/>
	</form>
	</div>
	{% if precio %}
	<div>
		<p>El precio promedio del producto que buscas es de: </p>
		<h3>$ {{ precio }}</h3>
	</div>
	{% endif %}
	<div>
		<p>Si tienes preguntas pendientes, da click en el siguiente botón para que las conteste por tí. </p>
		<form method="post" action="{% url 'landing:bot' %}" >
			{% csrf_token %}
			<input type="submit" placeholder="¡Contéstalas!">
		</form>
	</div>
</body>
</html>

landing/templates/landing/login.html
{% extends 'base.html' %}
{%load static%}
{% block section %}
<link rel="" type="text/css" href="{% static 'css/default.css' %">
<form action="{% url 'landing:index' %}" method="post">
    {% csrf_token %}
    <input type="text" id="username" placeholder="Username" required>
    <input type="password" id="password" placeholder="Password" required>
    <input type="submit" value="Login">
</form>
{% endblock section %}

landing/templates/landing/preguntas.html
{% for i in preguntas %}
	<h1>{{ i.title }}</h1>
	<img src="{{ i.image }}" alt="{{ i.title }}" />
	<ul>
		{% for question in i.questions %}
		<li>
			<p><strong>Pregunta</strong> {{ question.question }}</p>
			<p><strong>Respuesta:</strong> {{ question.answer }}</p>
		</li>
		{% endfor %}	
	</ul>
{% endfor %}
<a href="{% url 'landing:index' %}" method="post">Regresar al home.</a>